# 제어문

In [2]:
x_list = ['x1', 'x2']
y_list = ['y1', 'y2']

print("x y")
for x in x_list:
    for y in y_list:
        print(x,y)

x y
x1 y1
x1 y2
x2 y1
x2 y2


In [3]:
names = ['James', 'Rober', 'Lisa', 'Mary']
scores = [95,96,97,94]

In [4]:
for k in range(len(names)):
    print(names[k], scores[k])

James 95
Rober 96
Lisa 97
Mary 94


In [7]:
for name, score in zip(names, scores):
    print(name, score)

James 95
Rober 96
Lisa 97
Mary 94


In [11]:
i = 0
sum = 0

print("i sum")
while (sum<20):
    i = i + 1
    sum = sum + 1
    print( i, sum)


i sum
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17
18 18
19 19
20 20


In [15]:
k = 0
while True:
    k = k + 1
    
    if(k > 3):
        break
    
        
    print(k)

1
2
3


In [17]:
for k in range(20):
    if(k>2):
        break
        
    print(k)

0
1
2


In [19]:
for k in range(5):
    if (k==2):
        continue
        
    print(k)

0
1
3
4


In [24]:
k = 0
while True:
    k = k + 1
    
    if (k ==2):
        print("continue next")
        continue
    if(k>4):
        break
    print(k)

1
continue next
3
4


In [26]:
numbers = [1,2,3,4,5]
square = []

for i in numbers:
    square.append(i**2)
    
print(square)

[1, 4, 9, 16, 25]


In [28]:
numbers == [1,2,3,4,5]
square = []

for i in numbers:
    if i>=3:
        square.append(i**2)
        
print(square)

[9, 16, 25]


In [30]:
numbers = [1,2,3,4,5]
square = [i**2 for i in numbers if i>=3]

print(square)

[9, 16, 25]


# 입력과 출력

In [32]:
print("Hello Python")

Hello Python


In [33]:
print("Best", "python", "book")

Best python book


In [34]:
print("Best", "python", "book", sep="-:*:-")

Best-:*:-python-:*:-book


In [35]:
print("abcd"+"dfg")

abcddfg


In [36]:
print("Best", "python", "book" + ":", "This book")

Best python book: This book


In [37]:
x = 10
print(x)

10


In [39]:
name = "James"
ID_num = 789
print("Name:", name + ",", "ID Number:", ID_num)

Name: James, ID Number: 789


In [42]:
print("James is my friend.\nHe is Korean.")

James is my friend.
He is Korean.


In [46]:
print("James is mt friend.\n\nHe is Korean.")

James is mt friend.

He is Korean.


In [47]:
print("Welcome to")
print("python!")

Welcome to
python!


In [49]:
print("Welcome to \npython!")

Welcome to 
python!


In [6]:
name = "광재"
print("%s는 나의 친구입니다." % name)

광재는 나의 친구입니다.


In [7]:
r = 3
PI = 3.14159265358979
print("반지름: %d, 원주율: %f" % (r,PI))

반지름: 3, 원주율: 3.141593


In [9]:
animal_0 = "cat"
animal_1 = "dog"
animal_2 = "fox"

print("Animal: {0}".format(animal_0))
print("Animal: {0}, {1}, {2}".format(animal_0, animal_1, animal_2))

Animal: cat
Animal: cat, dog, fox


In [11]:
print("Animal: {1}, {2}, {0}".format(animal_0, animal_1, animal_2))

Animal: dog, fox, cat


In [13]:
name = "Tomas"
age = 10
a = 0.1234567890123456789
fmt_string = "String: {0}. Integer Number: {1}. Floating Number: {2}"
print(fmt_string.format(name, age, a))

String: Tomas. Integer Number: 10. Floating Number: 0.12345678901234568


In [14]:
a = 0.1234567890123456789
print("{0:.2f}, {0:.5f}".format(a))

0.12, 0.12346


In [15]:
yourName = input("당신의 이름은?")
print("당신은 {}이군요.".format(yourName))

당신의 이름은? 혜린


당신은 혜린이군요.


In [16]:
num = input("숫자를 입력하세요")
print("당신이 입력한 숫자는 {}입니다.".format(num))

숫자를 입력하세요 1


당신이 입력한 숫자는 1입니다.


In [19]:
a = input("정사각형 한 변의 길이는?")
area = int(a) ** 2
print("정사각형의 넓이: {}".format(area))

정사각형 한 변의 길이는? 4


정사각형의 넓이: 16


In [20]:
b = input("정사각형 한 변의 길이는?")
area = float(b) ** 2
print("정사각형의 넓이: {}".format(area))

정사각형 한 변의 길이는? 4


정사각형의 넓이: 16.0


# 함수

In [24]:
def my_func():
    print("My first function!")
    print("This is a function")

my_func()

My first function!
This is a function


In [25]:
def my_friend(friendName):
    print("{}는 나의 친구입니다.".format(friendName))
    
my_friend("철수")
my_friend("영미")

철수는 나의 친구입니다.
영미는 나의 친구입니다.


In [26]:
def my_student_info(name, school_ID, phonenumber):
    print("-----------------")
    print("-학생이름:", name)
    print("-학급번호:", school_ID)
    print("-전화번호:", phonenumber)
    
my_student_info("현아", "01", "01-234-567")

-----------------
-학생이름: 현아
-학급번호: 01
-전화번호: 01-234-567


In [30]:
def my_cal(x,y):
    z = x*y
    return z

my_cal(3,4)

12

In [32]:
a = 5

def func1():
    a = 1
    print("[func1] 지역 변수 a =", a)
    
def func2():
    a = 2
    print("[func2] 지역 변수 a =", a)
    
def func3():
    print("[func3] 전역 변수 a =", a)
    
def func4():
    global a
    a = 4
    print("[func4] 전역 변수 a =", a)
    
func1()
func2()
func3()
func4()

[func1] 지역 변수 a = 1
[func2] 지역 변수 a = 2
[func3] 전역 변수 a = 5
[func4] 전역 변수 a = 4


In [33]:
(lambda x : x**2) (3)

9

In [34]:
mySquare = lambda x : x**2
mySquare(2)

4

# 객체와 클래스

In [43]:
class Bicycle():
    
    def move(self, speed):
        print("자전거: 시속 {0}킬로미터 전진".format(speed))
    
    def turn(self, direction):
        print("자전거: {0}회전".format(direction))
              
    def stop(self):
        print("자전거({0}, {1}): 정지".format(self.wheel_size, self.color))

In [47]:
my_bicycle = Bicycle()

my_bicycle.wheel_size = 26
my_bicycle.color = 'black'

In [48]:
my_bicycle.move(30)
my_bicycle.turn('좌')
my_bicycle.stop()

자전거: 시속 30킬로미터 전진
자전거: 좌회전
자전거(26, black): 정지


In [56]:
your_bicycle = Bicycle()

your_bicycle.wheel_size = 30
your_bicycle.color = 'red'

In [57]:
your_bicycle.move(70)
your_bicycle.turn('우')
your_bicycle.stop()

자전거: 시속 70킬로미터 전진
자전거: 우회전
자전거(30, red): 정지


# 문자열과 텍스트 파일 데이터 다루기

In [58]:
coffee_menu_str = "에스프레소, 아메리카노, 카페라테, 카푸치노"
coffee_menu_str.split(',')

['에스프레소', ' 아메리카노', ' 카페라테', ' 카푸치노']

In [60]:
"에스프레소 아메리카노 카페라테 카푸치노".split(maxsplit=2)

['에스프레소', '아메리카노', '카페라테 카푸치노']

In [61]:
phone_number = "+82-01-2345-6789"
split_num = phone_number.split("-", 1)

print(split_num)
print("국내전화번호: {0}".format(split_num[1]))

['+82', '01-2345-6789']
국내전화번호: 01-2345-6789


In [1]:
str_f = "Python code."

print("찾는 문자열의 위치:", str_f.find("Python"))
print("찾는 문자열의 위치:", str_f.find("code"))
print("찾는 문자열의 위치:", str_f.find("n"))
print("찾는 문자열의 위지:", str_f.find("easy"))

찾는 문자열의 위치: 0
찾는 문자열의 위치: 7
찾는 문자열의 위치: 5
찾는 문자열의 위지: -1


In [2]:
str_c = "Python is powerful. Python is easy to learn. Python is open."

print("Python의 개수는?:", str_c.count("Python"))
print("powerful의 개수는?:", str_c.count("powerful"))
print("IPython의 개수는?", str_c.count("IPython"))

Python의 개수는?: 3
powerful의 개수는?: 1
IPython의 개수는? 0


In [3]:
str_se = "Python is powerful. Python is easy to learn."
print("Python으로 시작?:", str_se.startswith("Python"))
print("is로 시작?:", str_se.startswith("is"))
print(".로 끝?:", str_se.endswith("."))
print("learn으로 끝?:", str_se.endswith("learn"))

Python으로 시작?: True
is로 시작?: False
.로 끝?: True
learn으로 끝?: False


In [4]:
str_a = 'Python is fast. Python is friendly. Python is open.'
print(str_a.replace('Python', 'IPython'))
print(str_a.replace('Python', 'IPython', 2))

IPython is fast. IPython is friendly. IPython is open.
IPython is fast. IPython is friendly. Python is open.


# 데이터 분석을 위한 패키지

In [2]:
import numpy as np

In [3]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [8]:
a1.dtype

dtype('int32')

In [7]:
a2.dtype

dtype('float64')

In [9]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

In [11]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [14]:
b2 = np.arange(5)
b2.shape

(5,)

In [15]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.rand(2,3)

array([[0.62175515, 0.96234089, 0.83390233],
       [0.4410409 , 0.99163484, 0.33612841]])

In [18]:
np.random.rand()

0.9966043656802858

In [19]:
np.random.rand(2,3,4)

array([[[0.37379768, 0.05397404, 0.97863828, 0.67636618],
        [0.15198852, 0.63444665, 0.67474055, 0.10451224],
        [0.52617139, 0.32600631, 0.01371042, 0.16028289]],

       [[0.06114598, 0.8557015 , 0.98729355, 0.56822603],
        [0.21470339, 0.68162387, 0.2113296 , 0.82060021],
        [0.33144701, 0.22069066, 0.26093482, 0.51365433]]])

In [20]:
np.random.randint(10, size=(3,4))

array([[8, 7, 1, 8],
       [3, 3, 1, 4],
       [6, 1, 0, 8]])

In [26]:
np.random.randint(1,30)

3

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

In [28]:
arr1 + arr2

array([11, 22, 33, 44])

In [29]:
arr1 - arr2

array([ -9, -18, -27, -36])

In [30]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [4]:
arr1 > arr2

array([False, False, False, False])

In [3]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [7]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [10]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [11]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [4]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [6]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
import pandas as pd

In [8]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [10]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [11]:
s2 = pd.Series(['a','b','c',1,2,3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [12]:
import numpy as np

s3 = pd.Series([np.nan,10,30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [13]:
index_date = ['2018-10-07', '2018-10-08', '2018-10-09', '2018-10=10']
s4 = pd.Series([200,195,np.nan,205], index = index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10=10    205.0
dtype: float64

In [15]:
s5 = pd.Series({'국어': 100, '영어': 95, '수학': 90})
s5

국어    100
영어     95
수학     90
dtype: int64

In [16]:
pd.date_range(start='2019-01-01', end='2019-01-07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [17]:
pd.date_range(start='2019-01-01', periods = 7)

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [18]:
pd.DataFrame([[1,2,3,], [4,5,6], [7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [19]:
data_list = np.array([[10,20,30], [40,50,60], [70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [20]:
table_data = {'연도': [2015,2016,2016,2017,2017],
              '지사': ['한국', '한국', '미국', '한국', '미국'],
              '고객 수': [200,250,450,300,500]}
table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [22]:
pd.DataFrame(table_data)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [23]:
df = pd.DataFrame(table_data, columns=['연도', '지사', '고객 수'])
df

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [25]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [26]:
df.columns

Index(['연도', '지사', '고객 수'], dtype='object')

In [27]:
df.values

array([[2015, '한국', 200],
       [2016, '한국', 250],
       [2016, '미국', 450],
       [2017, '한국', 300],
       [2017, '미국', 500]], dtype=object)

In [28]:
table_data3 = {'봄': [256.5, 264.3, 215.9, 223.2, 312.8],
               '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
               '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
               '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [29]:
df3.mean()

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [30]:
df3.std()

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [33]:
df3.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [34]:
df3.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [35]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000